### ISSUE TITLE
Train result is not consistent with the original paper

### ISSUE THREAD

**Issue by xinkez** [deNsuh/segan-pytorch#16]
Hi, 
Thanks for your codes.  I use your codes to train the segan network. When the result came out, it is not consistent with the original paper. The noisy signal is denoised less. Have you compared your results with the original paper before?
Thanks in advance.

**Comment by dansuh17** [comment]
I have compared them, and it worked fine. However, it has been a while since I did that. Somehow, the codes in this repository are somewhat different from the code I used for testing. There are plans to refine this project soon (pytorch 1.0 is coming!). I will generate and post a link to samples generated by then :)
